spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  session:
    jdbc:
      initialize-schema: always
      table-name: spring_session

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
    show-sql: true

forgot-password:
  reset-password-message: "<p>Привет, %s!</p><p>Вы запросили сброс пароля.</p>
  <p>Перейдите по ссылке ниже, чтобы изменить свой пароль:</p><p><a href=\"%s\">Изменить мой пароль</a></p><br>
  <p>Пожалуйста, проигнорируйте это письмо, если вы его не запрашивали</p>"

email:
  regex: "^[a-zA-Z0-9._\\-%]+@(?:gmail\\.com|mail\\.ru|yandex\\.ru|vk\\.com)$"

cbr:
  url: "https://www.cbr-xml-daily.ru/daily_utf8.xml"

api:
  v1:
    prefix: /api/v1

jwt:
  secret: ${JWT_SECRET}
  lifetime: 900000