spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
    show-sql: true

forgot-password:
  resetPasswordMessage: "<p>Привет, %s!</p><p>Вы запросили сброс пароля.</p>
  <p>Перейдите по ссылке ниже, чтобы изменить свой пароль:</p><p><a href=\"%s\">Изменить мой пароль</a></p><br>
  <p>Пожалуйста, проигнорируйте это письмо, если вы его не запрашивали</p>"

dadata:
  url: https://cleaner.dadata.ru/api/v1/clean/email
  token: ${DADATA_TOKEN}
  secret: ${DADATA_SECRET}
